etcd:
  client:
    endpoints:
      - "127.0.0.1:2379"
    dialTimeout: 5s
    username: ""
    password: ""
  configSource:
    client:
      endpoints:
        - "127.0.0.1:2379"
      dialTimeout: 5s
    mode: kv
    prefix: /example/config/kv
    watch: true
    format: yaml
