yggdrasil:
  polaris:
    default:
      addresses:
        - "127.0.0.1:8091"
      config_addresses:
        - "127.0.0.1:8093"
      token: ""

  example:
    watched_key: "dd"
    config_source:
      sdk: default
      namespace: "default"
      fileGroup: "app"
      fileName: "service.yaml"
      subscribe: true
      mode: 0
      fetchTimeout: "2s"
