yggdrasil:
  polaris:
    default:
      addresses:
        - "127.0.0.1:8091"
      token: ""
    governance:
      config:
        sdk: default
        namespace: default
        callerService: "github.com.codesjoy.yggdrasil.contrib.polaris.example.client"
        callerNamespace: "default"
        routing:
          enable: true
          routers: []
          lbPolicy: ""
          timeout: 200ms
          retryCount: 0
          arguments: {}
        rateLimit:
          enable: false
          token: 1
          timeout: 200ms
          retryCount: 0
          arguments: {}
        circuitBreaker:
          enable: false

  balancer:
    polaris:
      type: polaris

  resolver:
    default:
      type: polaris
      config:
        sdk: default
        namespace: "default"
        protocols: ["grpc"]
        refreshInterval: "5s"
        timeout: "2s"
        retryCount: 0
        skipRouteFilter: true
        metadata: {}

  client:
    github.com.codesjoy.yggdrasil.contrib.polaris.example.server:
      resolver: default
      balancer: polaris

  interceptor:
    unary_client: "logging"
    stream_client: "logging"
