yggdrasil:
  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:
        address: ":55879"
    logger_level: info

  polaris:
    default:
      addresses:
        - "127.0.0.1:8091"
      token: ""

  registry:
    type: polaris
    config:
      sdk: default
      namespace: "default"
      serviceToken: ""
      ttl: "5s"
      autoHeartbeat: true
      timeout: "2s"
      retryCount: 0

  interceptor:
    unary_server: "logging"
    stream_server: "logging"

  logger:
    handler:
      default:
        type: "console"
        level: "info"
    writer:
      default:
        type: "console"
