yggdrasil:
  application:
    namespace: "prod"
    version: "v2026.01"
    metadata:
      env: "prod"
      region: "gz"
      lane: "blue"

  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:
        address: "127.0.0.1:55881"

  polaris:
    default:
      addresses:
        - "127.0.0.1:8091"

  registry:
    type: polaris
    config:
      sdk: default
      namespace: "prod"
      serviceToken: ""
      ttl: "5s"
      autoHeartbeat: true
      timeout: "2s"
      retryCount: 0
