server:
  port: 18000
  nodeID: "yggdrasil.example.xds.control-plane"

xds:
  configFile: "xds-config.yaml"
  watchInterval: 1s

yggdrasil:
  logger:
    handler:
      default:
        type: "console"
        level: "info"
    writer:
      default:
        type: "console"
